language: java

env:
  global:
    - secure: "QFelCXkmjAiBcKhtAeecGJqTu3WzeFk1LGsreE25y2DO8kV4pvf5gTGP9jwLybSGpA7AS11Ofqq7Mh9LJ21tPn59iyz0j2Z7YTjY+7P+Z+z7m4Wav0bKjdetZSgvqX9pFGmfmVHjGpMu0M3ixpRHxKpHhgZQYYgEWr9nNOtjLew="
    - secure: "FsmkRwqYYftyyPf13RetjCnPLOUislnw7IEcVmkW67L73aDPcdDQbVXe8ITpynrQOXQdbAWr9T8H+aEyEu6ddMuMpNFB9T1t75sSYt5FQ/NwDoeNX8hyCibcP8pLL8SrMxFInujLqzR/83cEkvPMCN86MEWVL0Snh/swqyERD80="

script: "./gradlew build -x spotlessCheck"

jdk:
  - oraclejdk8
  
install: ./gradlew assemble --stacktrace -x spotlessCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
    - ./gradlew uploadArchives -x spotlessCheck -Plocal=true
