language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
 
install: ./gradlew assemble -x spotlessJava --stacktrace

script: "./gradlew build -x spotlessJava"



