
language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9
 
install: ./gradlew assemble -x spotlessJava --stacktrace --no-daemon

script: "./gradlew build citest -x test -x spotlessJava --full-stacktrace --no-daemon --debug"

