language: java
script: "./gradlew build  -x spotlessJava --debug --full-stacktrace"
jdk:
  - oraclejdk8
install: ./gradlew assemble -x spotlessJava --stacktrace

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

